# Form implementation generated from reading ui file 'frame_relat.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frameRelat(object):
    def setupUi(self, frameRelat):
        frameRelat.setObjectName("frameRelat")
        frameRelat.resize(831, 371)
        frameRelat.setStyleSheet("background-color: rgb(241, 242, 254);")
        self.centralwidget = QtWidgets.QWidget(frameRelat)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 811, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        frameRelat.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(frameRelat)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 831, 21))
        self.menubar.setObjectName("menubar")
        frameRelat.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(frameRelat)
        self.statusbar.setObjectName("statusbar")
        frameRelat.setStatusBar(self.statusbar)

        self.retranslateUi(frameRelat)
        QtCore.QMetaObject.connectSlotsByName(frameRelat)

    def retranslateUi(self, frameRelat):
        _translate = QtCore.QCoreApplication.translate
        frameRelat.setWindowTitle(_translate(
            "frameRelat", "Relatório de Placas capturadas"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("frameRelat", "Id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("frameRelat", "Data"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("frameRelat", "Placa"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("frameRelat", "Cor"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("frameRelat", "Fabricanta"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("frameRelat", "Tipo"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("frameRelat", "Ano"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("frameRelat", "Modelo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frameRelat = QtWidgets.QMainWindow()
    ui = Ui_frameRelat()
    ui.setupUi(frameRelat)
    frameRelat.show()
    sys.exit(app.exec())
