# Form implementation generated from reading ui file 'main_frame.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt6 import QtCore, QtGui, QtWidgets, uic
from PyQt6.QtWidgets import *
from PyQt6.QtGui import *
import threading
from ImageCreatedHandler import *
from GetVideo import startCamera

thread = threading.Thread(target=ImageHandler)
thread.daemon = True
thread.start()


def actionVehicleRegistrations():
    print("Abrindo Registro de veículos...")


def actionStartCamera():
    print("Iniciando o video...")
    startCamera()


def actionExit():
    print("Encerrando a Aplicação, Até logo...")
    sys.exit()


class Second(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super(Second, self).__init__(parent)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(1097, 733)

        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1097, 21))
        self.menubar.setObjectName("menubar")
        self.menuBalanca = QtWidgets.QMenu(self.menubar)
        self.menuBalanca.setFont(font)
        self.menuBalanca.setObjectName("menuBalanca")
        self.menuSair = QtWidgets.QMenu(self.menubar)
        self.menuSair.setFont(font)
        self.menuSair.setObjectName("menuSair")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionIniciar_Camera = QtGui.QAction(MainWindow)
        self.actionIniciar_Camera.setFont(font)
        self.actionIniciar_Camera.setObjectName("actionIniciar_Camera")
        self.actionIniciar_Camera.triggered.connect(actionStartCamera)
        self.actionVeiculos_Registrados = QtGui.QAction(MainWindow)
        self.actionVeiculos_Registrados.setFont(font)
        self.actionVeiculos_Registrados.setObjectName(
            "actionVeiculos_Registrados")
        self.actionVeiculos_Registrados.triggered.connect(
            actionVehicleRegistrations)
        self.actionSair = QtGui.QAction(MainWindow)
        self.actionSair.setFont(font)
        self.actionSair.setObjectName("actionSair")
        self.actionSair.triggered.connect(actionExit)
        self.menuBalanca.addAction(self.actionIniciar_Camera)
        self.menuBalanca.addSeparator()
        self.menuBalanca.addAction(self.actionVeiculos_Registrados)
        self.menuSair.addAction(self.actionSair)
        self.menubar.addAction(self.menuBalanca.menuAction())
        self.menubar.addAction(self.menuSair.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Principal"))
        self.menuBalanca.setTitle(_translate("MainWindow", "Monitoramento"))
        self.menuSair.setTitle(_translate("MainWindow", "Sair"))
        self.actionIniciar_Camera.setText(
            _translate("MainWindow", "Iniciar Camera"))
        self.actionIniciar_Camera.setShortcut(
            _translate("MainWindow", "Ctrl+C"))
        self.actionVeiculos_Registrados.setText(
            _translate("MainWindow", "Veiculos Registrados"))
        self.actionVeiculos_Registrados.setShortcut(
            _translate("MainWindow", "Ctrl+R"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
        self.actionSair.setShortcut(_translate("MainWindow", "Ctrl+Q"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    # segunda_tela = uic.loadUi("frame_relat.ui")
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui2 = Ui_MainWindow()
    ui2.setupUi(MainWindow)
    MainWindow.setGeometry(50, 60, 300, 100)
    MainWindow.show()
    startCamera()
    sys.exit(app.exec())
