# Form implementation generated from reading ui file 'main_frame.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt6 import QtCore, QtGui, QtWidgets, uic
from PyQt6.QtWidgets import *
from PyQt6.QtCore import Qt
from PyQt6.QtGui import *
from ImageCreatedHandler import *
from frame_relat2 import *
from GetVideo import *


def actionVehicleRegistration():
    if not Window2.isVisible():
        print("Abrindo Registro de veículos...")
        Window2.show()
    else:
        print("A janela de Registro de veículos já está aberta...")
        Window2.raise_()


def actionStartCamera():
    startCamera(source, pos_linha, offset, largura_min, altura_min)
    print("iniciando Monitoramento!")


def actionExit():
    print("Encerrando a Aplicação, Até logo...")
    sys.exit()


class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(1097, 733)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1097, 21))
        self.menubar.setObjectName("menubar")
        self.menuBalanca = QtWidgets.QMenu(self.menubar)
        self.menuBalanca.setFont(font)
        self.menuBalanca.setObjectName("menuMonitoramento")
        self.menuSair = QtWidgets.QMenu(self.menubar)
        self.menuSair.setFont(font)
        self.menuSair.setObjectName("menuSair")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionIniciar_Camera = QtGui.QAction(MainWindow)
        self.actionIniciar_Camera.setFont(font)
        self.actionIniciar_Camera.setObjectName("actionIniciar_Camera")
        self.actionIniciar_Camera.triggered.connect(actionStartCamera)

        self.actionVeiculos_Registrados = QtGui.QAction(MainWindow)
        self.actionVeiculos_Registrados.setFont(font)
        self.actionVeiculos_Registrados.setObjectName(
            "actionVeiculos_Registrados")
        self.actionVeiculos_Registrados.triggered.connect(
            actionVehicleRegistration)
        self.actionSair = QtGui.QAction(MainWindow)
        self.actionSair.setFont(font)
        self.actionSair.setObjectName("actionSair")
        self.actionSair.triggered.connect(actionExit)
        self.menuBalanca.addAction(self.actionIniciar_Camera)
        self.menuBalanca.addSeparator()
        self.menuBalanca.addAction(self.actionVeiculos_Registrados)
        self.menuSair.addAction(self.actionSair)
        self.menubar.addAction(self.menuBalanca.menuAction())
        self.menubar.addAction(self.menuSair.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowFlag(Qt.WindowType.WindowCloseButtonHint, False)
        MainWindow.setWindowTitle(_translate("MainWindow", "Principal"))
        self.menuBalanca.setTitle(_translate("MainWindow", "Monitoramento"))
        self.menuSair.setTitle(_translate("MainWindow", "Sair"))
        self.actionIniciar_Camera.setText(
            _translate("MainWindow", "Iniciar Monitoramento"))
        self.actionIniciar_Camera.setShortcut(
            _translate("MainWindow", "Ctrl+C"))
        self.actionVeiculos_Registrados.setText(
            _translate("MainWindow", "Veiculos Registrados"))
        self.actionVeiculos_Registrados.setShortcut(
            _translate("MainWindow", "Ctrl+R"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
        self.actionSair.setShortcut(_translate("MainWindow", "Ctrl+Q"))


def main():
    global Window2
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    Window2 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui2 = Ui_frameRelat()
    ui2.setupUi(Window2)
    MainWindow.setGeometry(0, 0, 300, 100)
    MainWindow.show()
    actionStartCamera()
    sys.exit(app.exec())


if __name__ == "__main__":
    main()
    
